# Generated by Django 3.1 on 2020-08-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200826_1637'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_question',
            name='choice',
            field=models.CharField(default='E', max_length=3),
        ),
        migrations.AlterField(
            model_name='stu_question',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='qpaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question_paper'),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sturesults_db',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
